import os
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
DB_PATH = BASE_DIR / "ioec.db"
TAXONOMY_PATH = BASE_DIR / "taxonomy" / "taxonomy_v1.json"

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
LLM_MODEL = "claude-opus-4-6"
LLM_MAX_TOKENS = 8000

EXTRACTION_CONFIDENCE_MIN = float(os.getenv("EXTRACTION_CONFIDENCE_MIN", "0.55"))
CLUSTERING_SIMILARITY_THRESHOLD = float(os.getenv("CLUSTERING_SIMILARITY_THRESHOLD", "0.86"))
MATCH_SIMILARITY_THRESHOLD = float(os.getenv("MATCH_SIMILARITY_THRESHOLD", "0.84"))

CHUNK_TARGET_TOKENS = 1200
CHUNK_OVERLAP_RATIO = 0.12
QUOTE_SNIPPET_MAX_LEN = 240
MAX_SECONDARY_CATEGORIES = 2

EMBEDDING_MODEL = "all-MiniLM-L6-v2"
